# -*- coding: utf-8 -*-
"""ucgen.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pOdPJVieVNNntzH3mfOvSLyfGsXpgb4t
"""

import glob
import os

folders = ['HGG', 'LGG']
writeText = open('train.txt', 'w')
for folder in folders:
    sub_folders = glob.glob(folder + os.sep + '*')
    for sub_folder in sub_folders:
        files = glob.glob(sub_folder + '/*_flair.nii.gz')
        if len(files) <= 0:
            continue
        writeText.write(os.sep + files[0] + ', ' + os.sep + files[0].replace('flair', 'seg') + '\n')
writeText.close()