# -*- coding: utf-8 -*-
"""ucloadData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dE5DtFP0H28yQkE4dt3gTLcbEZ6QVpJO

nibabel==2.3.0
opencv>=3.0.0
pytorch==0.3.1
skimage>=0.13.1
pickle==
graphviz==0.9
"""

import pickle
import nibabel as nib
import numpy as np

"""Create another .py file w/ '/' fix"""

class LoadData:
    def __init__(self, data_dir, data_dir_val, classes, cached_data_file, normVal=1.10):
        self.data_dir = data_dir
        self.data_dir_val = data_dir_val
        self.classes = classes
        self.classWeights = np.ones(self.classes, dtype=np.float32)
        self.normVal = normVal
        self.trainImList = list()
        self.valImList = list()
        self.trainAnnotList = list()
        self.valAnnotList = list()
        self.cached_data_file = cached_data_file

    def compute_class_weights(self, histogram):
        normHist = histogram / np.sum(histogram)
        for i in range(self.classes):
            self.classWeights[i] = 1 / (np.log(self.normVal + normHist[i]))
            print('normHist: ', normHist, ' shape: ', classWeights.shape, ' classWeights: ', classWeights)

    def readFile(self, fileName, trainStg=False):

        if trainStg:
            global_hist = np.zeros(self.classes, dtype=np.float32)

        no_files = 0

        data_dir = self.data_dir if trainStg else self.data_dir_val
        print('data_dir: ', data_dir)
        print('data_dir_val: ', data_dir_val)

        #with open(data_dir + '/' + fileName, 'r') as textFile:
        with open(data_dir + fileName, 'r') as textFile:
            for line in textFile:
                #line = textFile.read()
                line_arr = line.split(',')
                ##print(line)
                img_file = ((data_dir).strip() + '/' + line_arr[0].strip()).strip()
                #img_file = ((data_dir).strip() + line_arr[0].strip()).strip()
                label_file = ((data_dir).strip() + '/' + line_arr[1].strip()).strip()
                #label_file = ((data_dir).strip() + line_arr[1].strip()).strip()
                print('label_file: ', label_file)

                label_img = nib.load(label_file).get_data()

                print('label_img unchanged: ', label_img)
                
                
                # There is no label with value 3 in BRATS dataset. We rename label 4 as 3.
                label_img[label_img == 4] = 3           # this line may be the problem why the 3rd elmt
                                                        # in each per_class list is 0
                print('label_img changed: ', label_img) # it may need to be double checked
                
                
                
                unique_values = np.unique(label_img)
                max_val = max(unique_values)
                min_val = min(unique_values)

                if trainStg:
                    hist = np.histogram(label_img, self.classes)
                    global_hist += hist[0]
                    self.trainImList.append(img_file)
                    self.trainAnnotList.append(label_file)
                else:
                    self.valImList.append(img_file)
                    self.valAnnotList.append(label_file)

                if max_val > (self.classes - 1) or min_val < 0:
                    print('Some problem with labels. Please check.')
                    print('Label Image ID: ' + label_file)
                no_files += 1

        if trainStg:
            #compute the class imbalance information
            self.compute_class_weights(global_hist)

        return 0

    def processData(self):
        print('Processing training data')
        return_val = self.readFile('train.txt', True)
        
        print('Processing validation data')
        return_val1 = self.readFile('val.txt')

        print('Pickling data')
        if return_val ==0 and return_val1 ==0:
            data_dict = dict()
            data_dict['trainIm'] = self.trainImList
            data_dict['trainAnnot'] = self.trainAnnotList
            data_dict['valIm'] = self.valImList
            data_dict['valAnnot'] = self.valAnnotList
            data_dict['classWeights'] = self.classWeights

            pickle.dump(data_dict, open(self.cached_data_file, "wb"))
            return data_dict
        return None

